import type {Device,HistorySample,LoginResponse,Policy,Quota,VpnStatus} from '../types/api';
const baseUrl=(import.meta.env.VITE_API_BASE_URL as string|undefined)?.replace(/\/$/,'')??'';
export class ApiError extends Error{constructor(public readonly status:number,message:string){super(message);this.name='ApiError';}}
let unauthorizedHandler:(()=>void)|undefined;
export function onUnauthorized(handler:()=>void){unauthorizedHandler=handler;return()=>{unauthorizedHandler=undefined;};}
function token(){return sessionStorage.getItem('nm_token');}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set('Accept','application/json');if(init.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const t=token();if(t)headers.set('Authorization',`Bearer ${t}`);const r=await fetch(`${baseUrl}${path}`,{...init,headers,credentials:'include'});if(r.status===401){unauthorizedHandler?.();throw new ApiError(401,'Authentication required');}if(!r.ok){let m=`Request failed (${r.status})`;try{const b=await r.json() as {error?:string};if(b.error)m=b.error;}catch{}throw new ApiError(r.status,m);}if(r.status===204)return undefined as T;return r.json() as Promise<T>;}
async function mergeLiveStatus(devices:Device[]){try{const live=await request<Array<{mac:string;online:boolean}>>('/api/devices/live');const map=new Map(live.map(x=>[x.mac.toLowerCase(),x]));return devices.map(d=>({...d,online:map.get(d.mac.toLowerCase())?.online??d.online}));}catch{return devices;}}
export const api={login:(username:string,password:string)=>request<LoginResponse>('/api/auth/login',{method:'POST',body:JSON.stringify({username,password})}),logout:()=>request<void>('/api/auth/logout',{method:'POST'}),devices:async()=>mergeLiveStatus(await request<Device[]>('/api/devices')),device:async(mac:string)=>{const d=await request<Device>(`/api/devices/${encodeURIComponent(mac)}`);return (await mergeLiveStatus([d]))[0]},policy:(mac:string)=>request<Policy>(`/api/devices/${encodeURIComponent(mac)}/policy`),quota:(mac:string)=>request<Quota>(`/api/devices/${encodeURIComponent(mac)}/quota`),block:(mac:string)=>request<{blocked:boolean}>(`/api/devices/${encodeURIComponent(mac)}/block`,{method:'POST'}),unblock:(mac:string)=>request<{blocked:boolean}>(`/api/devices/${encodeURIComponent(mac)}/unblock`,{method:'POST'}),acceptIdentity:(mac:string,acknowledgment:string)=>request<{accepted:boolean}>(`/api/devices/${encodeURIComponent(mac)}/accept-unconfirmed-identity`,{method:'POST',body:JSON.stringify({acknowledgment})}),setDownload:(mac:string,rateMbps:string)=>request<Policy>(`/api/devices/${encodeURIComponent(mac)}/download-limit`,{method:'POST',body:JSON.stringify({rateMbps})}),clearDownload:(mac:string)=>request<Policy>(`/api/devices/${encodeURIComponent(mac)}/download-limit`,{method:'DELETE'}),setUpload:(mac:string,rateMbps:string)=>request<Policy>(`/api/devices/${encodeURIComponent(mac)}/upload-limit`,{method:'POST',body:JSON.stringify({rateMbps})}),clearUpload:(mac:string)=>request<Policy>(`/api/devices/${encodeURIComponent(mac)}/upload-limit`,{method:'DELETE'}),updatePolicy:(mac:string,body:Partial<Pick<Policy,'quota'|'quotaPeriod'|'quotaAction'>>)=>request<Policy>(`/api/devices/${encodeURIComponent(mac)}/policy`,{method:'PATCH',body:JSON.stringify(body)}),resetQuota:(mac:string)=>request<Quota>(`/api/devices/${encodeURIComponent(mac)}/quota/reset`,{method:'POST'}),history:(id:number,range:'day'|'week'|'month')=>request<HistorySample[]>(`/api/traffic/history?device_id=${id}&range=${range}`),vpnStatus:()=>request<VpnStatus>('/api/vpn/status'),vpnConfig:(vmessLink:string)=>request<unknown>('/api/vpn/config',{method:'POST',body:JSON.stringify({vmessLink})}),vpnEnable:()=>request<unknown>('/api/vpn/enable',{method:'POST'}),vpnDisable:()=>request<unknown>('/api/vpn/disable',{method:'POST'})};
export function liveTrafficUrl(){const configured=baseUrl||window.location.origin;const u=new URL('/api/traffic/live',configured);u.protocol=u.protocol==='https:'?'wss:':'ws:';return u.toString();}
