import type { FastifyInstance } from "fastify";
import type { PolicyCatalogService } from "../../../application/policies/PolicyCatalogService.js";
const json=(value:unknown)=>JSON.parse(JSON.stringify(value,(_,v)=>typeof v==="bigint"?v.toString():v));
const idParams={type:"object",required:["id"],additionalProperties:false,properties:{id:{type:"string",pattern:"^[1-9][0-9]*$"}}};
export async function policyCatalogRoutes(app:FastifyInstance, service:PolicyCatalogService):Promise<void>{
  app.get("/api/profiles",async()=>json(await service.profiles()));
  app.post<{Body:{name:string;description?:string|null;downloadLimit?:string|null;uploadLimit?:string|null;quota?:string|null;quotaPeriod?:string|null}}>("/api/profiles",{schema:{body:{type:"object",required:["name"],additionalProperties:false,properties:{name:{type:"string",minLength:1,maxLength:120},description:{type:["string","null"],maxLength:1000},downloadLimit:{type:["string","null"],pattern:"^[0-9]+$"},uploadLimit:{type:["string","null"],pattern:"^[0-9]+$"},quota:{type:["string","null"],pattern:"^[0-9]+$"},quotaPeriod:{type:["string","null"],enum:["daily","weekly","monthly",null]}}}}},async r=>service.createProfile({name:r.body.name,description:r.body.description??null,downloadLimit:r.body.downloadLimit==null?null:BigInt(r.body.downloadLimit),uploadLimit:r.body.uploadLimit==null?null:BigInt(r.body.uploadLimit),quota:r.body.quota==null?null:BigInt(r.body.quota),quotaPeriod:r.body.quotaPeriod??null}).then(json));
  app.patch<{Params:{id:string};Body:{name?:string;description?:string|null;downloadLimit?:string|null;uploadLimit?:string|null;quota?:string|null;quotaPeriod?:string|null}}>("/api/profiles/:id",{schema:{params:idParams}},async r=>service.updateProfile(Number(r.params.id),{...(r.body.name===undefined?{}:{name:r.body.name}),...(r.body.description===undefined?{}:{description:r.body.description}),...(r.body.quotaPeriod===undefined?{}:{quotaPeriod:r.body.quotaPeriod}),...(r.body.downloadLimit===undefined?{}:{downloadLimit:r.body.downloadLimit===null?null:BigInt(r.body.downloadLimit)}),...(r.body.uploadLimit===undefined?{}:{uploadLimit:r.body.uploadLimit===null?null:BigInt(r.body.uploadLimit)}),...(r.body.quota===undefined?{}:{quota:r.body.quota===null?null:BigInt(r.body.quota)})}).then(json));
  app.delete<{Params:{id:string}}>("/api/profiles/:id",{schema:{params:idParams}},async r=>{await service.deleteProfile(Number(r.params.id));return {deleted:true};});
  app.get("/api/schedules",async()=>json(await service.schedules()));
  app.post<{Body:{name:string;description?:string|null;rules:any[]}}>("/api/schedules",async r=>service.createSchedule({name:r.body.name,description:r.body.description??null,rules:r.body.rules??[]}).then(json));
  app.patch<{Params:{id:string};Body:{name?:string;description?:string|null;rules?:any[]}}>("/api/schedules/:id",{schema:{params:idParams}},async r=>service.updateSchedule(Number(r.params.id),r.body).then(json));
  app.delete<{Params:{id:string}}>("/api/schedules/:id",{schema:{params:idParams}},async r=>{await service.deleteSchedule(Number(r.params.id));return {deleted:true};});
  app.get<{Params:{id:string}}>("/api/devices/:id/port-rules",{schema:{params:idParams}},async r=>json(await service.portRules(Number(r.params.id))));
  app.post<{Params:{id:string};Body:{name:string;protocol:string;port:number;action:string;enabled?:boolean}}>("/api/devices/:id/port-rules",{schema:{params:idParams,body:{type:"object",required:["name","protocol","port","action"],additionalProperties:false,properties:{name:{type:"string",minLength:1,maxLength:120},protocol:{type:"string",enum:["tcp","udp"]},port:{type:"integer",minimum:1,maximum:65535},action:{type:"string",enum:["allow","block"]},enabled:{type:"boolean"}}}}},async r=>service.createPortRule({deviceId:Number(r.params.id),name:r.body.name,protocol:r.body.protocol,port:r.body.port,action:r.body.action,enabled:r.body.enabled??true}).then(json));
  app.delete<{Params:{id:string}}>("/api/port-rules/:id",{schema:{params:idParams}},async r=>{await service.deletePortRule(Number(r.params.id));return {deleted:true};});
}
