import { promises as fs } from "node:fs";
import { dirname } from "node:path";
import type { DeviceRepository } from "../../domain/repositories/DeviceRepository.js";
import type { DevicePolicyRepository } from "../../domain/repositories/DevicePolicyRepository.js";
import { config } from "../../config.js";

export interface DnsmasqReloader {
  reload(): Promise<void>;
}

export class DhcpReservationService {
  private timer: NodeJS.Timeout | undefined;
  private running = false;

  constructor(
    private readonly devices: DeviceRepository,
    private readonly policies: DevicePolicyRepository,
    private readonly path = config.setup.dhcpReservationsPath,
    private readonly reloader?: DnsmasqReloader,
    private readonly intervalMs = 10_000,
  ) {}

  async start(): Promise<void> {
    if (this.timer) return;
    await this.reconcile();
    this.timer = setInterval(() => void this.reconcile(), this.intervalMs);
  }

  stop(): void {
    if (!this.timer) return;
    clearInterval(this.timer);
    this.timer = undefined;
  }

  async reconcile(): Promise<boolean> {
    if (this.running) return false;
    this.running = true;

    try {
      const rows: string[] = ["# Generated by network-control-system; do not edit."];

      for (const device of await this.devices.findAll()) {
        const policy = await this.policies.findByDeviceId(device.id);
        // Any persisted device policy makes the device actively managed,
        // including profiles and schedules in addition to limits/quota/block.
        if (!policy || !device.ip) continue;
        rows.push(`dhcp-host=${device.mac.toString()},${device.ip.toString()}`);
      }

      const next = `${rows.join("\n")}\n`;
      let current = "";
      try {
        current = await fs.readFile(this.path, "utf8");
      } catch {
        // Missing file means dnsmasq state must be regenerated.
      }

      if (current === next) return false;

      await fs.mkdir(dirname(this.path), { recursive: true });
      try {
        await fs.copyFile(this.path, `${this.path}.bak`);
      } catch {
        // First setup may not have an existing reservation file.
      }

      const temporary = `${this.path}.tmp-${process.pid}`;
      await fs.writeFile(temporary, next, "utf8");
      await fs.rename(temporary, this.path);

      if (this.reloader) await this.reloader.reload();
      return true;
    } finally {
      this.running = false;
    }
  }
}
