import { promises as fs } from "node:fs";
import { dirname } from "node:path";
import type { DeviceRepository } from "../../domain/repositories/DeviceRepository.js";
import type { DevicePolicyRepository } from "../../domain/repositories/DevicePolicyRepository.js";
import { config } from "../../config.js";
export class DhcpReservationService {
  constructor(private readonly devices:DeviceRepository,private readonly policies:DevicePolicyRepository,private readonly path=config.setup.dhcpReservationsPath){}
  async reconcile(){const rows:string[]=["# Generated by network-control-system; do not edit."];for(const device of await this.devices.findAll()){const policy=await this.policies.findByDeviceId(device.id);const managed=policy&&(policy.blocked||policy.downloadLimit!==null||policy.uploadLimit!==null||policy.quota!==null);if(!managed||!device.ip)continue;rows.push(`dhcp-host=${device.mac.toString()},${device.ip.toString()}`);}await fs.mkdir(dirname(this.path),{recursive:true});try{await fs.copyFile(this.path,`${this.path}.bak`);}catch{}const temporary=`${this.path}.tmp`;await fs.writeFile(temporary,`${rows.join("\n")}\n`,"utf8");await fs.rename(temporary,this.path);}
}
