import { promises as fs } from "node:fs";
import { dirname, join } from "node:path";

export interface SetupProbe { run(command:string,args:string[]):Promise<{stdout:string;stderr:string}>; }
export interface SetupInterface { name:string; mac:string|null; state:string; addresses:string[]; kind:string|null; }
export interface SetupNetworkReport { interfaces:SetupInterface[]; defaultUplink:string|null; uplinkSubnets:Record<string,string[]>; proposedClientSubnets:string[]; errors:string[]; }
export interface SetupReport { root:boolean; port53Free:boolean; ifbAvailable:boolean; firewallManager:string|null; timeSynchronized:boolean; errors:string[]; }
export interface SetupPaths { configPath:string; dnsmasqPath:string; snapshotDir:string; leasePath?:string; }
export interface SetupApplyInput { clientInterface:string; uplinkInterface:string; clientSubnet:string; uplinkBandwidthMbps:number; dashboardPort:number; sshPort:number; dnsServers:string[]; clientGatewayIp?:string; vpnTunnelInterface?:string; vpnTunAddress?:string; singBoxConfigPath?:string; dhcpReservationsPath?:string; activate?:boolean; }
export interface SetupHealth { clientInterface:boolean; gatewayReachable:boolean; dhcpLeaseFile:boolean; outboundConnectivity:boolean; errors:string[]; }
export interface SetupApplyResult { applied:boolean; configPath:string; renderedFiles:string[]; health:SetupHealth; rolledBack:boolean; errors:string[]; }
export interface SetupDiagnostics { interface:string|null; linkSpeedMbps:number|null; duplex:string|null; usbSpeed:string|null; warnings:string[]; errors:string[]; }

const cidr=/^(\d{1,3}(?:\.\d{1,3}){3})\/(\d{1,2})$/;
const iface=/^[a-zA-Z0-9_.:-]{1,32}$/;
const ipv4=/^(?:\d{1,3}\.){3}\d{1,3}$/;

export class SetupService {
  constructor(private readonly probe:SetupProbe, private readonly paths:SetupPaths={configPath:process.env.SYSTEM_CONFIG_PATH??"/etc/network-control-system/config.env",dnsmasqPath:process.env.DNSMASQ_CONFIG_PATH??"/etc/dnsmasq.d/network-control-clients.conf",snapshotDir:process.env.SETUP_SNAPSHOT_DIR??"/var/lib/network-control/backups",leasePath:process.env.DHCP_LEASE_PATH??"/var/lib/misc/dnsmasq.leases"}){}
  async preflight():Promise<SetupReport>{const errors:string[]=[];const root=typeof process.getuid!=="function"||process.getuid()===0;const port=await this.safe("ss",["-H","-lun","sport","=",":53"]);const port53Free=port.stdout.trim()==="";const ifb=await this.safe("modprobe",["ifb"]);const ifbAvailable=ifb.ok;const ufw=await this.safe("ufw",["status"]);const firewallManager=ufw.ok&&/Status:\s+active/i.test(ufw.stdout)?"ufw":null;const timed=await this.safe("timedatectl",["show","-p","NTPSynchronized","--value"]);const timeSynchronized=timed.stdout.trim()==="yes";if(!root)errors.push("root privileges are required");if(!port53Free)errors.push("UDP port 53 is occupied; dnsmasq will use port=0");if(!ifbAvailable)errors.push("ifb kernel module is unavailable");if(firewallManager)errors.push("ufw is active and must be reviewed before nftables changes");if(!timeSynchronized)errors.push("system clock is not synchronized");return {root,port53Free,ifbAvailable,firewallManager,timeSynchronized,errors};}
  async inspectNetwork():Promise<SetupNetworkReport>{const errors:string[]=[];const links=await this.readJson("ip",["-j","link","show"]);const addresses=await this.readJson("ip",["-j","-4","addr","show"]);const routes=await this.readJson("ip",["-j","route","show","default"]);const addressMap=new Map<string,string[]>();for(const row of Array.isArray(addresses)?addresses:[]){const name=String(row.ifname??"");addressMap.set(name,Array.isArray(row.addr_info)?row.addr_info.filter((a:any)=>a.family==="inet").map((a:any)=>`${a.local}/${a.prefixlen}`):[]);}const interfaces=(Array.isArray(links)?links:[]).map((row:any):SetupInterface=>({name:String(row.ifname??""),mac:typeof row.address==="string"?row.address:null,state:String(row.operstate??"UNKNOWN"),addresses:addressMap.get(String(row.ifname??""))??[],kind:typeof row.link_type==="string"?row.link_type:null})).filter(x=>x.name&&x.name!=="lo");const defaultUplink=Array.isArray(routes)&&typeof routes[0]?.dev==="string"?routes[0].dev:null;const uplinkSubnets:Record<string,string[]>={};for(const item of interfaces)uplinkSubnets[item.name]=item.addresses;const used=interfaces.flatMap(x=>x.addresses.map(networkOf).filter((x):x is string=>Boolean(x)));const proposedClientSubnets=["192.168.50.0/24","192.168.60.0/24","10.77.0.0/24","172.31.77.0/24"].filter(candidate=>!used.some(value=>overlaps(candidate,value)));if(!defaultUplink)errors.push("No default-route interface detected");if(!interfaces.length)errors.push("No usable network interfaces detected");if(!proposedClientSubnets.length)errors.push("No non-overlapping private client subnet was found");return {interfaces,defaultUplink,uplinkSubnets,proposedClientSubnets,errors};}
  async diagnostics(interfaceName?:string):Promise<SetupDiagnostics>{const network=await this.inspectNetwork();const selected=interfaceName??network.defaultUplink;const warnings:string[]=[];const errors:string[]=[];if(!selected){return {interface:null,linkSpeedMbps:null,duplex:null,usbSpeed:null,warnings,errors:["No interface available for diagnostics"]};}if(!iface.test(selected)||!network.interfaces.some(item=>item.name===selected))return {interface:selected,linkSpeedMbps:null,duplex:null,usbSpeed:null,warnings,errors:["Interface is not a detected interface"]};const link=await this.safe("ethtool",[selected]);const speed=link.stdout.match(/Speed:\s*(\d+)Mb\/s/i)?.[1];const duplex=link.stdout.match(/Duplex:\s*(\S+)/i)?.[1]??null;const usb=await this.safe("lsusb",["-t"]);const usbSpeed=usb.stdout.match(/\b(12M|480M|5000M|10000M)\b/)?.[1]??null;const linkSpeedMbps=speed?Number(speed):null;if(linkSpeedMbps!==null&&linkSpeedMbps<100)warnings.push(`Low negotiated link speed: ${linkSpeedMbps} Mbps`);if(usbSpeed==="12M")warnings.push("USB adapter is operating at Full-Speed (12M); hardware may cap throughput");if(!link.ok)errors.push(`Unable to read ethtool diagnostics for ${selected}`);return {interface:selected,linkSpeedMbps,duplex,usbSpeed,warnings,errors};}
  async apply(input:SetupApplyInput):Promise<SetupApplyResult>{const validation=this.validateInput(input);if(validation.length)return this.failed(validation);const network=await this.inspectNetwork();const selected=new Set(network.interfaces.map(item=>item.name));const selectionErrors:string[]=[];if(!selected.has(input.clientInterface))selectionErrors.push(`client interface not found: ${input.clientInterface}`);if(!selected.has(input.uplinkInterface))selectionErrors.push(`uplink interface not found: ${input.uplinkInterface}`);const uplinkRanges=network.uplinkSubnets[input.uplinkInterface]??[];if(uplinkRanges.length&&!uplinkRanges.some(range=>overlaps(input.clientSubnet,networkOf(range)??range)))selectionErrors.push("client subnet conflicts with Single-Interface requirement: it must overlap the uplink subnet");if(selectionErrors.length)return this.failed(selectionErrors);const preflight=await this.preflight();if(preflight.errors.length)return this.failed(preflight.errors);const gateway=input.clientGatewayIp??firstHost(input.clientSubnet);const rendered=this.render(input,gateway);const snapshot=await this.snapshot();try{await this.writeAtomic(this.paths.configPath,rendered.config);await this.writeAtomic(this.paths.dnsmasqPath,rendered.dnsmasq);if(input.activate!==false){await this.probe.run("ip",["addr","replace",`${gateway}/${prefix(input.clientSubnet)}`,"dev",input.clientInterface]);await this.probe.run("systemctl",["daemon-reload"]);await this.probe.run("systemctl",["enable","dnsmasq","network-control-enforcement.service","network-control-backend.service"]);await this.probe.run("systemctl",["restart","dnsmasq"]);}const health=await this.health(input.clientInterface,gateway);if(health.errors.length)throw new Error(health.errors.join("; "));return {applied:true,configPath:this.paths.configPath,renderedFiles:[this.paths.configPath,this.paths.dnsmasqPath],health,rolledBack:false,errors:[]};}catch(error){await this.rollback(snapshot);const message=error instanceof Error?error.message:String(error);return {applied:false,configPath:this.paths.configPath,renderedFiles:[],health:{clientInterface:false,gatewayReachable:false,dhcpLeaseFile:false,outboundConnectivity:false,errors:[message]},rolledBack:true,errors:[message]};}}
  async rollbackLatest():Promise<void>{const snapshot=join(this.paths.snapshotDir,"latest");for(const [target,name] of [[this.paths.configPath,"config.env"],[this.paths.dnsmasqPath,"clients.conf"]] as const){try{await fs.copyFile(join(snapshot,name),target);}catch{}}try{await this.probe.run("nft",["-f",join(snapshot,"nftables.bak")]);}catch{}}
  private async snapshot():Promise<string>{const dir=join(this.paths.snapshotDir,`setup-${Date.now()}`);await fs.mkdir(dir,{recursive:true});for(const [target,name] of [[this.paths.configPath,"config.env"],[this.paths.dnsmasqPath,"clients.conf"]] as const){try{await fs.copyFile(target,join(dir,name));}catch{}}try{const nft=await this.probe.run("nft",["list","ruleset"]);await fs.writeFile(join(dir,"nftables.bak"),nft.stdout,"utf8");}catch{}const latest=join(this.paths.snapshotDir,"latest");await fs.mkdir(latest,{recursive:true});for(const [target,name] of [[this.paths.configPath,"config.env"],[this.paths.dnsmasqPath,"clients.conf"]] as const){try{await fs.copyFile(target,join(latest,name));}catch{}}try{await fs.copyFile(join(dir,"nftables.bak"),join(latest,"nftables.bak"));}catch{}return dir;}
  private failed(errors:string[]):SetupApplyResult{return {applied:false,configPath:this.paths.configPath,renderedFiles:[],health:{clientInterface:false,gatewayReachable:false,dhcpLeaseFile:false,outboundConnectivity:false,errors},rolledBack:false,errors};}
  private async rollback(snapshot:string){for(const [target,name] of [[this.paths.configPath,"config.env"],[this.paths.dnsmasqPath,"clients.conf"]] as const){try{await fs.copyFile(join(snapshot,name),target);}catch{}}try{await this.probe.run("nft",["-f",join(snapshot,"nftables.bak")]);}catch{}}
  private async health(client:string,gateway:string):Promise<SetupHealth>{const errors:string[]=[];const link=await this.safe("ip",["-j","addr","show","dev",client]);const clientInterface=link.ok&&link.stdout.includes(client);const gatewayReachable=(await this.safe("ping",["-c","1","-W","1",gateway])).ok;const lease=(await this.safe("cat",[this.paths.leasePath??process.env.DHCP_LEASE_PATH??"/var/lib/misc/dnsmasq.leases"]));const dhcpLeaseFile=lease.ok&&lease.stdout.trim().length>0;const outbound=(await this.safe("ping",["-c","1","-W","2","-I",client,"1.1.1.1"])).ok;if(!clientInterface)errors.push("client interface is not configured");if(!gatewayReachable)errors.push("client gateway is not reachable");if(!dhcpLeaseFile)errors.push("dnsmasq has not issued a lease");if(!outbound)errors.push("outbound connectivity test failed");return {clientInterface,gatewayReachable,dhcpLeaseFile,outboundConnectivity:outbound,errors};}
  private render(input:SetupApplyInput,gateway:string){const [start,end]=dhcpRange(input.clientSubnet);const vpnInterface=input.vpnTunnelInterface??process.env.VPN_TUN_INTERFACE??"tun0";const vpnAddress=input.vpnTunAddress??process.env.VPN_TUN_ADDRESS??"172.19.0.1/30";const singBoxPath=input.singBoxConfigPath??process.env.SING_BOX_CONFIG_PATH??"/etc/sing-box/config.json";const reservations=input.dhcpReservationsPath??process.env.DHCP_RESERVATIONS_PATH??"/var/lib/misc/network-control-reservations.conf";const config=[`CLIENT_INTERFACE=${input.clientInterface}`,`UPLINK_INTERFACE=${input.uplinkInterface}`,`CLIENT_SUBNET=${input.clientSubnet}`,`CLIENT_GATEWAY_IP=${gateway}`,`DHCP_RANGE_START=${start}`,`DHCP_RANGE_END=${end}`,`DNS_SERVERS=${input.dnsServers.join(",")}`,`DASHBOARD_PORT=${input.dashboardPort}`,`SSH_PORT=${input.sshPort}`,`UPLINK_BANDWIDTH_MBPS=${input.uplinkBandwidthMbps}`,"NETWORK_MODE=single-interface-ifb",`VPN_TUN_INTERFACE=${vpnInterface}`,`VPN_TUN_ADDRESS=${vpnAddress}`,`SING_BOX_CONFIG_PATH=${singBoxPath}`,`DHCP_RESERVATIONS_PATH=${reservations}`].join("\n")+"\n";const dnsmasq=["# Generated by network-control-system; do not edit.","bind-interfaces",`interface=${input.clientInterface}`,"port=0",`dhcp-range=${start},${end},12h`,`dhcp-option=3,${gateway}`,`dhcp-option=6,${input.dnsServers.join(",")}`].join("\n")+"\n";return {config,dnsmasq};}
  private validateInput(input:SetupApplyInput){const errors:string[]=[];if(!iface.test(input.clientInterface)||!iface.test(input.uplinkInterface))errors.push("interface selections are invalid");const network=cidr.exec(input.clientSubnet);if(!network||prefix(input.clientSubnet)>30||network[1]!.split(".").some(part=>Number(part)>255))errors.push("clientSubnet must be a valid IPv4 network with prefix <= 30");if(input.clientGatewayIp&&(!ipv4.test(input.clientGatewayIp)||input.clientGatewayIp.split(".").some(part=>Number(part)>255)))errors.push("clientGatewayIp must be a valid IPv4 address");if(input.vpnTunnelInterface&&!iface.test(input.vpnTunnelInterface))errors.push("VPN tunnel interface is invalid");for(const value of [input.vpnTunAddress,input.singBoxConfigPath,input.dhcpReservationsPath])if(value!==undefined&&(!value.trim()||/[\r\n]/.test(value)))errors.push("setup path/address values must not be empty or contain newlines");if(!Number.isInteger(input.uplinkBandwidthMbps)||input.uplinkBandwidthMbps<=0)errors.push("uplink bandwidth must be a positive integer");if(!Number.isInteger(input.dashboardPort)||input.dashboardPort<1||input.dashboardPort>65535||!Number.isInteger(input.sshPort)||input.sshPort<1||input.sshPort>65535)errors.push("management ports must be valid TCP ports");if(input.dnsServers.some(x=>!ipv4.test(x)||x.split(".").some(part=>Number(part)>255)))errors.push("DNS servers must be IPv4 addresses");return errors;}
  private async readJson(command:string,args:string[]){try{return JSON.parse((await this.probe.run(command,args)).stdout);}catch{return [];}}
  private async safe(command:string,args:string[]){try{return {ok:true,...await this.probe.run(command,args)};}catch(error){return {ok:false,stdout:"",stderr:error instanceof Error?error.message:String(error)};}}
  private async writeAtomic(path:string,value:string){await fs.mkdir(dirname(path),{recursive:true});const temp=`${path}.tmp-${process.pid}`;await fs.writeFile(temp,value,{encoding:"utf8",mode:0o600});await fs.rename(temp,path);}
}

function prefix(value:string){return Number(cidr.exec(value)?.[2]??0);}
function firstHost(value:string){const address=value.split("/")[0]??"0.0.0.0";const parts=address.split(".").map(Number);parts[3]=(parts[3]??0)+1;return parts.join(".");}
function ipNumber(value:string){return value.split(".").map(Number).reduce((n,p)=>(n<<8)+p,0)>>>0;}
function numberIp(n:number){return [(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255].join(".");}
function networkOf(value:string){const match=cidr.exec(value);if(!match)return null;const bits=Number(match[2]);if(bits<0||bits>32)return null;const mask=bits===0?0:(0xffffffff<<(32-bits))>>>0;const network=ipNumber(match[1]!)&mask;return `${numberIp(network)}/${bits}`;}
function overlaps(a:string,b:string){const am=cidr.exec(a),bm=cidr.exec(b);if(!am||!bm)return false;const bits=Math.min(Number(am[2]),Number(bm[2]));const mask=bits===0?0:(0xffffffff<<(32-bits))>>>0;return (ipNumber(am[1]!)&mask)===(ipNumber(bm[1]!)&mask);}
function dhcpRange(value:string){const match=cidr.exec(value);if(!match)throw new Error("invalid subnet");const bits=Number(match[2]);const network=ipNumber(match[1]!)&((0xffffffff<<(32-bits))>>>0);return [numberIp(network+100),numberIp(network+250)];}
