CREATE TYPE "IdentitySource" AS ENUM ('DHCP', 'DHCP_CONFIRMED_PROXY', 'STATIC_ARP', 'PROXY_UNCONFIRMED', 'PROXY_ACCEPTED_BY_ADMIN');

ALTER TABLE "devices"
  ADD COLUMN "identitySource" "IdentitySource" NOT NULL DEFAULT 'DHCP';
